### ISSUE TITLE
Pointer are not listed

### ISSUE THREAD

**Issue by CuriousTommy** [BullyWiiPlaza/Wii-U-Pointer-Search#1]
When finding pointers, I am normally able to get their pointers without issue. However, when I tried to find a pointer to make the no music code for Super Mario 3D, this happens:
![image](https://cloud.githubusercontent.com/assets/3105794/17753273/fd596e74-6483-11e6-94b5-940d4b19315f.png)

I don't know if this also happen in WIndows also. Here is a link to the two ram dumps that I used:
https://www.dropbox.com/s/1wptinb0s3rt45r/No%20Music.zip?dl=0

**Comment by BullyWiiPlaza** [comment]
Thanks for another good report. I tried it out and the same thing happened on Windows:
![2016-08-18_00h01_38](https://cloud.githubusercontent.com/assets/7620135/17754884/0adc70f2-64d7-11e6-8c73-19847033a473.png)
Strange indeed. Maybe too many pointers or ran out of memory? I'll check it further

EDIT:
The error is the following:

```
java.util.concurrent.ExecutionException: java.io.EOFException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.wiiudev.gecko.pointer.search.searcher.UniversalPointerSearcher.performPointerSearch(UniversalPointerSearcher.java:137)
    at com.wiiudev.gecko.pointer.swing.UniversalPointerSearcherGUI.doPointerSearch(UniversalPointerSearcherGUI.java:340)
    at com.wiiudev.gecko.pointer.swing.UniversalPointerSearcherGUI.access$700(UniversalPointerSearcherGUI.java:20)
    at com.wiiudev.gecko.pointer.swing.UniversalPointerSearcherGUI$4.doInBackground(UniversalPointerSearcherGUI.java:301)
    at com.wiiudev.gecko.pointer.swing.UniversalPointerSearcherGUI$4.doInBackground(UniversalPointerSearcherGUI.java:287)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
    at java.io.RandomAccessFile.readInt(RandomAccessFile.java:803)
    at com.wiiudev.gecko.pointer.search.pointer.MemoryPointer.reachesTargetAddress(MemoryPointer.java:71)
    at com.wiiudev.gecko.pointer.search.pointer.MemoryPointer.supportsAllMemoryDumps(MemoryPointer.java:28)
    at com.wiiudev.gecko.pointer.search.searcher.UniversalPointerSearcher.validatePointer(UniversalPointerSearcher.java:262)
    at com.wiiudev.gecko.pointer.search.searcher.UniversalPointerSearcher.checkForPointerDepth2(UniversalPointerSearcher.java:241)
    at com.wiiudev.gecko.pointer.search.searcher.UniversalPointerSearcher.performPointerSearch(UniversalPointerSearcher.java:198)
    at com.wiiudev.gecko.pointer.search.searcher.UniversalPointerSearcher.lambda$performPointerSearch$0(UniversalPointerSearcher.java:126)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    ... 3 more
```

**Comment by BullyWiiPlaza** [comment]
Fixed, I found the issue. A stupid programming error.

![2016-08-18_01h59_10](https://cloud.githubusercontent.com/assets/7620135/17757493/727e8924-64e7-11e6-8621-2c4fe6a15aa8.png)
